switch:
    ## Data Process
    kLidarFlatProcess: false
    kLidarEdgeProcess: false
    kFisheyeFlatProcess: false  # true: use the fisheye flat image process method 
    kFisheyeEdgeProcess: false  # false: use the fisheye edge process method

    ## Registration, Colorization and Mapping
    # view
    kCreateDensePcd: false
    kViewRegistration: false
    kFullViewMapping: false
    kFullViewColorization: false
    # spot
    kSpotRegistration: false
    kGlobalMapping: false
    kGlobalColoredMapping: false

    ## Calibration and Optimization cost analysis
    kCeresOptimization: false
    kParamsAnalysis: false
    
spot:
    kOneSpot: -1  # -1: means run all the spots, other means run the specific spot index 

essential:
    kDatasetName: "lh3_global"
    kNumSpots: 5
    kNumViews: 5
    kFisheyeRows: 2048
    kFisheyeCols: 2448
    kLiDARTopic: "/livox/lidar"
    kResolution: 1000
    kAngleStep: 25

