switch:
    ## Data Process
    kLidarFlatProcess: true
    kFisheyeFlatProcess: false

    ## Registration, Colorization and Mapping
    # view
    kCreateDensePcd: false
    kViewRegistration: false
    kFullViewMapping: false

    ## Calibration and Optimization cost analysis
    kCeresOptimization: true
    kParamsAnalysis: true
    
    # spot
    kSpotRegistration: false
    kGlobalMapping: true

    # colorization
    kFullViewColorization: true
    kGlobalColoredMapping: true

spot:
    kOneSpot: 0  # -1: means run all the spots, other means run the specific spot index 

essential:
    kLidarTopic: "/livox/lidar"
    kDatasetName: "parking"
    kNumSpots: 6
    kNumViews: 5
    kFisheyeRows: 2048
    kFisheyeCols: 2448
    kAngleInit: -50
    kAngleStep: 25

