switch:
    ## Data Process
    kLidarFlatProcess: false
    kFisheyeFlatProcess: false

    ## Registration, Colorization and Mapping
    # view
    kCreateDensePcd: false
    kViewRegistration: false
    kFullViewMapping: false

    ## Calibration and Optimization cost analysis
    kCeresOptimization: false
    kMultiSpotsOptimization: false
    kParamsAnalysis: false
    
    # spot
    kSpotRegistration: true
    kGlobalMapping: false

    # colorization
    kFullViewColorization: false
    kGlobalColoredMapping: false

spot:
    kOneSpot: 3  # -1: means run all the spots, other means run the specific spot index 

essential:
    kLidarTopic: "/livox/lidar"
    kDatasetName: "liyuan"
    kNumSpots: 7
    kNumViews: 5
    kFisheyeRows: 2048
    kFisheyeCols: 2448
    kAngleInit: -50
    kAngleStep: 25

