switch:
    ## Registration, Colorization and Mapping
    # view
    kCreateDensePcd: false
    kViewRegistration: false
    kFullViewMapping: false

    ## Data Process
    kLidarFlatProcess: false
    kFisheyeFlatProcess: false

    ## Calibration and Optimization cost analysis
    kCeresOptimization: true
    kMultiSpotsOptimization: true
    kAnalysis: false
    
    # spot
    kSpotRegistration: false
    kGlobalMapping: false

    # colorization
    kSpotColorization: true
    kGlobalColoredMapping: true

    kGlobalUniformSampling: false

spot:
    kOneSpot: -1  # -1: means run all the spots, other means run the specific spot index 

essential:
    kLidarTopic: "/livox/lidar"
    # kDatasetName: "bs"
    # kNumSpots/: 5
    # kDatasetName: "crf"
    # kNumSpots: 1
    # kDatasetName: "rb1"
    # kNumSpots: 1
    kDatasetName: "bs_hall"
    kNumSpots: 5
    # kDatasetName: "room"
    # kNumSpots: 1
    # kDatasetName: "parking"
    # kNumSpots: 6
    kNumViews: 5
    kFisheyeRows: 2048
    kFisheyeCols: 2448
    kAngleInit: -50
    kAngleStep: 25

transform:
    rx: -0.0
    ry: 3.13
    rz: -0.861748
    tx: -13.21285
    ty: -23.67988
    tz: -0.310397
