switch:
    ## Data Process
    kLidarFlatProcess: false
    kFisheyeFlatProcess: false

    ## Registration, Colorization and Mapping
    # view
    kCreateDensePcd: false
    kViewRegistration: false
    kFullViewMapping: false

    ## Calibration and Optimization cost analysis
    kCeresOptimization: false
    kMultiSpotsOptimization: false
    kParamsAnalysis: false
    
    # spot
    kSpotRegistration: false
    kGlobalMapping: false

    # colorization
    kFullViewColorization: true
    kGlobalColoredMapping: true

spot:
    kOneSpot: -1  # -1: means run all the spots, other means run the specific spot index 

essential:
    kLidarTopic: "/livox/lidar"
    # kDatasetName: "lh3_global"
    # kNumSpots: 5
    # kDatasetName: "crf"
    # kNumSpots: 1
    # kDatasetName: "rb1"
    # kNumSpots: 1
    kDatasetName: "bs_hall"
    kNumSpots: 5
    kNumViews: 5
    kFisheyeRows: 2048
    kFisheyeCols: 2448
    kAngleInit: -50
    kAngleStep: 25

transform:
    rx: -0.0228948
    ry: 0.027074
    rz: 0.776748
    tx: -4.83285
    ty: -2.08588
    tz: -0.110397
