switch:
    ## Data Process
    kLidarFlatProcess: false
    kLidarEdgeProcess: false
    kFisheyeFlatProcess: false  # true: use the fisheye flat image process method 
    kFisheyeEdgeProcess: false  # false: use the fisheye edge process method

    ## Registration, Colorization and Mapping
    # view
    kCreateDensePcd: true
    kViewRegistration: false
    kFullViewMapping: false
    kFullViewColorization: false
    # spot
    kSpotRegistration: false
    kGlobalMapping: false
    kGlobalColoredMapping: false

    ## Calibration and Optimization cost analysis
    kCeresOptimization: false
    kParamsAnalysis: false
    
spot:
    kOneSpot: 0  # -1: means run all the spots, other means run the specific spot index 

essential:
    kLidarTopic: "/livox/lidar"
    kDatasetName: "liyuan"
    kNumSpots: 7
    kNumViews: 5GlobalMapping
    kFisheyeRows: 2048
    kFisheyeCols: 2448
    kAngleInit: -50
    kAngleStep: 25

